### PR TITLE
Showing error locations

### PR DESCRIPTION
**Pull request by stocker4141**
Related to issue #24 
The BoardMatcher class was adapted to add more information to its output.
At the end of lines with errors a string like: `<!> at: 25 difference: "2   ║"` will be appended, where 25 is the index of the error and "2   ║" is the String that follows the error in the expected output. 
In a sequence of boards, only the first board with an error will be printed to output an extension to print all the boards instead is possible - see the appendDescription Method in BoardMatcher.java.
The BoardMatcher is now used also in the fileTests.

Example of the output (generated by never printing a 2 in the ocean):
```
10) testInputOutputFile[10](FileTest)
java.lang.AssertionError: The GUI output for test tricky_example_missing is not as expected.
Expected: expected
╔════════╤═══╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   │   2   ║ <!> at: 25 difference: 2   ║
║  │  │  │   │   │ 3 │       ║
║  │4 │  │   │   │   │       ║
║  └──┘6 │   │ 5 │   │       ║
╚════════╧═══╧═══╧═══╧═══════╝
     but: was
╔════════╤═══╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   │       ║ <!> at: 25 difference: 2   ║
║  │  │  │   │   │ 3 │       ║
║  │4 │  │   │   │   │       ║
║  └──┘6 │   │ 5 │   │       ║
╚════════╧═══╧═══╧═══╧═══════╝
```

In order to use StringUtils from (http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html) the corresponding jar file was included (with License and Notice statements). 
Is that okay or should I create my own implementation of the difference and indexOfDifference methods?

### CODE REVIEW

**Comment by alessiogambi** [comment]
Hi, sure, you can go on and implement the difference and indexOfDifference. Regarding StringUtils mine was just a suggestion, but I think we can include in the libs folder also commons-lang3.

Is there a reason, why the same text,  ` <!> at: 25 difference: 2   ║`, appears twice in your log?

Maybe  can we consider to highlight the error (at least the first one) using `^` like the java compiler does?
Something on those lines:

```
expected:
╔════════╤═══╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   │   2   ║ <<
║  │  │  │   │   │ 3 │       ║
║  │4 │  │   │   │   │       ║
║  └──┘6 │   │ 5 │   │       ║
╚════════╧═══╧═══╧═══╧═══════╝
                         ^
but was:
╔════════╤═══╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   │       ║  <<
║  │  │  │   │   │ 3 │       ║
║  │4 │  │   │   │   │       ║
║  └──┘6 │   │ 5 │   │       ║
╚════════╧═══╧═══╧═══╧═══════╝
                         ^

 <!> at: 25 difference: expected '2' got ' ' 
```

or we can show only the relevant lines, like this?

```
╔════════╤═══╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   │       ║ 
-------------------------^
```

**Comment by stocker4141** [comment]
The only reasons for the same output appearing twice is that i recycled the code for outputing the expected board and actual board and I thought it is useful to indicate at both locations that an error occurred.

I agree that the indication with these arrow like the java compiler is very helpful.
Should only the wrong character be printed or is something like this a better result:

```
expected:
╔════════╤═══╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   │   2   ║ <<
║  │  │  │   │   │ 3 │       ║
║  │4 │  │   │   │   │       ║
║  └──┘6 │   │ 5 │   │       ║
╚════════╧═══╧═══╧═══╧═══════╝
                         ^
but was:
╔════════╤═══╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   │       ║  <<
║  │  │  │   │   │ 3 │       ║
║  │4 │  │   │   │   │       ║
║  └──┘6 │   │ 5 │   │       ║
╚════════╧═══╧═══╧═══╧═══════╝
                         ^

 <!> at: 25 difference: expected '│   2   ║' got '│       ║'
```
Where the <!> message would be something like the following in case a message box is displayed.
```
 <!> at: 2 difference: expected '│ Nice tie! │' got '│       │'
```

The way i would go about this is searching outwards from the error for stop characters (borders and corners) in the expected output and then outputing the relevant substrings. There are quite a few edge cases when performing this search so I have to give it some more thought, but in general this should be possible as well.

**Comment by alessiogambi** [comment]
I would say to keep this as easy as possible. Also, the message might be simply an indication of what's going on. If we realize that we can do better later, we'll do otherwise, we don't

**Comment by stocker4141** [comment]
Current outputs:

Case with 1 error:
```
4) testThatGivenTrickyInputsTheProgramOutputsCorrectly(TrickyInputTest)
java.lang.AssertionError:
Expected: expected
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   2   ║  << !
║  │  │  │   │ 3 │       ║
║  │4 │  │   │   │       ║
║  └──┘6 │ 5 │   │       ║
╚════════╧═══╧═══╧═══════╝
                     ^
     but: was
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │       ║  << !
║  │  │  │   │ 3 │       ║
║  │4 │  │   │   │       ║
║  └──┘6 │ 5 │   │       ║
╚════════╧═══╧═══╧═══════╝
                     ^
<!> at line 1 expected: '2' got: ' '
```

Case with 2 errors:
```
3) testThatGivenTrickyDrawingInputsTheProgramOutputsCorrectly(TrickyInputTest)
java.lang.AssertionError:
Expected: expected
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   2   ║  << !
║  │  │  │   │   │   3   ║     !
║  │4 │  │   │   │       ║
║  └──┘6 │ 5 │   │       ║
╚════════╧═══╧═══╧═══════╝
                     ^
     but: was
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │       ║  << !
║  │  │  │   │   │       ║     !
║  │4 │  │   │   │       ║
║  └──┘6 │ 5 │   │       ║
╚════════╧═══╧═══╧═══════╝
                     ^
<!> at line 1 expected: '2' got: ' '
```

I kept the check for multiple lines being wrong but only implemented the "bonus" message for the first error. That should cover us for now.

**Comment by alessiogambi** [comment]
I think the second example is a bit confusing. It seems that you know already where the output differs from the expectation (I can see two `!`). So why not generating two messages? Because this complicates the thing. For example, should you show up arrows also there, how to distinguish the first from the second error?

My suggestion is that we show only the first error, and we clearly tell on the message that this is the FIRST error that we encounter and there might be others. I feel that this is more close to how regular assertions work: if an assertion triggers, the following assertions are not even checked.

**Comment by stocker4141** [comment]
I was more focused on the added convenience of seeing all the lines with errors but i agree the visualization gets confusing.

Output with the new commit for the case with 2 errors is now:
```
3) testThatGivenTrickyDrawingInputsTheProgramOutputsCorrectly(TrickyInputTest)
java.lang.AssertionError:
Expected: expected
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   2   ║  <<
║  │  │  │   │   │   3   ║
║  │4 │  │   │   │       ║
║  └──┘6 │ 5 │   │       ║
╚════════╧═══╧═══╧═══════╝
                     ^
     but: was
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │       ║  <<
║  │  │  │   │   │       ║
║  │4 │  │   │   │       ║
║  └──┘6 │ 5 │   │       ║
╚════════╧═══╧═══╧═══════╝
                     ^
First difference at line 1 expected: '2' got: ' '
```

**Comment by alessiogambi** [comment]
I think we can see if more or better ideas come to mind and  eventually create a new pull request to include them

**Comment by Kombustor** [comment]
Great work!

**Pull request merged**
