### PR TITLE
add test data

### PR DESCRIPTION
**Pull request by mhrimaz**
`FILENAME_input.txt` represent input data and `FILENAME_output.txt` represent output text.

### CODE REVIEW

**Comment by Kombustor** [comment]
Are you currently working on a solution to run tests against these files? Is this even desirable? @alessiogambi 

Otherwise I'd take the favour.

**Comment by mhrimaz** [comment]
I am currently not sure about the outputs (should we print the final state or not?). But if I have the confirmation about that, I would write the test cases against these files in JS. Maybe you can do that in Java @Kombustor

**Comment by Kombustor** [comment]
I think @alessiogambi already answered that in Stud.IP ([here](https://studip.uni-passau.de/studip/plugins.php/coreforum/index/index/7bf30033689b549f217ea79ab34c3d23?cid=c8f37738b0b1a2fad9cf4175046e8fd9&again=yes#7bf30033689b549f217ea79ab34c3d23)). The final state shoudn't be printed out, but the message "over it".

**Comment by Kombustor** [comment]
When we get the confirmation from @alessiogambi I'd love to do it in java.
You would have to add me as a developer to your fork, then I can extend this PR.

**Comment by mhrimaz** [comment]
@Kombustor you don't need to. After @alessiogambi merged this PR, you can create your own fork and write the java codes. However, you can start right now. Just open the input file, read the first line, invoke `String::split(" ")` method, and give that as input to the program and compare the whole output with the output file of the test case.
If you can double-check the outputs, we will have more confidence in the test data.

**Comment by Kombustor** [comment]
Sure, if he merges this PR without the actual implementations that'd be the way to go!

**Comment by alessiogambi** [comment]
Hi,
I am fine to use input and output "files" for testing the application. However, you need also to commit the actual tests that make use you the files.

**Review by alessiogambi — APPROVED** [review]

**Pull request merged**
